# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/SimpleRX_constrains.xdc

# IP: ip/clk_wiz_2/clk_wiz_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_2 || ORIG_REF_NAME==clk_wiz_2} -quiet] -quiet

# XDC: ip/clk_wiz_2/clk_wiz_2_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_2 || ORIG_REF_NAME==clk_wiz_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_2/clk_wiz_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_2 || ORIG_REF_NAME==clk_wiz_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_2/clk_wiz_2_ooc.xdc
